include(Catch)

add_executable(vkp_tests
  cluster/slot_test.cpp
  cluster/topology_test.cpp
  core/smoke_test.cpp
  core/buffer_test.cpp
  core/byte_queue_test.cpp
  io/event_loop_test.cpp
  io/task_test.cpp
  io/wait_queue_test.cpp
  proxy/command_table_test.cpp
  proxy/cluster_routing_test.cpp
  proxy/proxy_test.cpp
  proxy/router_test.cpp
  proxy/worker_pool_test.cpp
  resp/parser_test.cpp
  resp/serializer_test.cpp
  resp/value_test.cpp
)
target_link_libraries(vkp_tests
  PRIVATE
    vkp_options
    vkp_lib
    Catch2::Catch2WithMain
    tomlplusplus::tomlplusplus
    xxHash::xxhash
)

catch_discover_tests(vkp_tests)
